version: '3.8'

services:
  api:
    build:
      context: ./OneIncTestApp.API
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  build-ui:
    image: node:20
    working_dir: /app
    volumes:
      - ./OneIncTestApp.Web:/app
    command: >
      sh -c "npm install && npm run build --omit=dev"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./OneIncTestApp.Web/dist/one-inc-test-app:/usr/share/nginx/html:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - "8080:80"
    depends_on:
      - api
      - build-ui
    networks:
      - app-network

networks:
  app-network:
    driver: bridge